### ISSUE TITLE
DocumentInfo

### ISSUE THREAD

**Issue by pushist1y** [themehrdad/NetTelebot#1]
In file DocumentInfo.cs there's string:
Thumb = new PhotoSizeInfo(jsonObject["thumb"].Value<JObject>());
which obviously does not belong there and causes errors

**Comment by themehrdad** [comment]
@pushist1y : Thanks for your feedback. Actually Thumb can be part of the Document, but it is optional. So I updated the code to read the value only if it is available.

Please have a look at Telegram Bot API. Thumb is optional:

https://core.telegram.org/bots/api#document

**Comment by pushist1y** [comment]
Yeah, you are right. Thanks for response anyway.
