### ISSUE TITLE
CustomKeyboard

### ISSUE THREAD

**Issue by xale76** [themehrdad/NetTelebot#4]
I've read in telegram api doc that I can request location in the button by passing a object (with optional field request_location set to true) instead of a simple string. How too do that with your class?
Thank you

**Comment by vertigra** [comment]
Hi,
You about this https://core.telegram.org/bots/api#keyboardbutton ?

**Comment by vertigra** [comment]
Added https://github.com/themehrdad/NetTelebot/blob/devel/NetTelebot/Type/Keyboard/KeyboardButton.cs
